name = "smartappinfo-worker"
main = "worker.js"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[env.production]
name = "smartappinfo-worker"
route = "smartappinfo.com/*"

# Environment variables for Pages
[env.production.vars]
NEXT_PUBLIC_API_URL = "https://smart-app-info-backend.vercel.app"
NEXT_PUBLIC_FRONTEND_URL = "https://smartappinfo.pages.dev"
